<a href="https://colab.research.google.com/github/yiwenwangANU/Machine_Learning/blob/main/Binary_Classification_of_dataset_Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Explore the data

In [54]:
import zipfile

zip_ref = zipfile.ZipFile('titanic.zip')
zip_ref.extractall()
zip_ref.close()

In [136]:
import pandas as pd

training_set = pd.read_csv('train.csv')
test_set = pd.read_csv('gender_submission.csv').join(pd.read_csv('test.csv').set_index('PassengerId'),
                                                     on='PassengerId') 
training_set

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [133]:
test_set

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [109]:
training_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [57]:
training_set.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [137]:
# Drop PassengerId, Name, Ticket
training_set = training_set.drop(columns = ['PassengerId', 'Name', 'Ticket'])
test_set = test_set.drop(columns = ['PassengerId', 'Name', 'Ticket'])

In [122]:
training_set, test_set

(     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
 0           0       3    male  22.0      1      0   7.2500   NaN        S
 1           1       1  female  38.0      1      0  71.2833   C85        C
 2           1       3  female  26.0      0      0   7.9250   NaN        S
 3           1       1  female  35.0      1      0  53.1000  C123        S
 4           0       3    male  35.0      0      0   8.0500   NaN        S
 ..        ...     ...     ...   ...    ...    ...      ...   ...      ...
 886         0       2    male  27.0      0      0  13.0000   NaN        S
 887         1       1  female  19.0      0      0  30.0000   B42        S
 888         0       3  female   NaN      1      2  23.4500   NaN        S
 889         1       1    male  26.0      0      0  30.0000  C148        C
 890         0       3    male  32.0      0      0   7.7500   NaN        Q
 
 [891 rows x 9 columns],
      Pclass     Sex   Age  SibSp  Parch      Fare Cabin Embarked
 0     

##Take care of missing data

In [138]:
for col in training_set.columns.values:
  print(f"In {col}, there are {training_set[col].isnull().sum()} nan value")

In Survived, there are 0 nan value
In Pclass, there are 0 nan value
In Sex, there are 0 nan value
In Age, there are 177 nan value
In SibSp, there are 0 nan value
In Parch, there are 0 nan value
In Fare, there are 0 nan value
In Cabin, there are 687 nan value
In Embarked, there are 2 nan value


In [139]:
training_set = training_set.drop(columns = ['Cabin'])
test_set = test_set.drop(columns = ['Cabin'])

In [140]:
from sklearn.impute import SimpleImputer
import numpy as np

imputer = SimpleImputer(strategy='most_frequent', missing_values=np.nan)
imputer = imputer.fit(training_set)
training_set.iloc[:,:] = imputer.transform(training_set)
training_set

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female  24.0      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [141]:
for col in training_set.columns.values:
  print(f"In {col}, there are {training_set[col].isnull().sum()} nan value")

In Survived, there are 0 nan value
In Pclass, there are 0 nan value
In Sex, there are 0 nan value
In Age, there are 0 nan value
In SibSp, there are 0 nan value
In Parch, there are 0 nan value
In Fare, there are 0 nan value
In Embarked, there are 0 nan value


In [142]:
imputer = SimpleImputer(strategy='most_frequent', missing_values=np.nan)
imputer = imputer.fit(test_set)
test_set.iloc[:,:] = imputer.transform(test_set)

In [143]:
X_train = training_set.iloc[:, 1:].values
y_train = training_set.iloc[:, 0].values

X_test = test_set.iloc[:, 1:].values
y_test = test_set.iloc[:, 0].values

In [144]:
X_train, X_test

(array([[3, 'male', 22.0, ..., 0, 7.25, 'S'],
        [1, 'female', 38.0, ..., 0, 71.2833, 'C'],
        [3, 'female', 26.0, ..., 0, 7.925, 'S'],
        ...,
        [3, 'female', 24.0, ..., 2, 23.45, 'S'],
        [1, 'male', 26.0, ..., 0, 30.0, 'C'],
        [3, 'male', 32.0, ..., 0, 7.75, 'Q']], dtype=object),
 array([[3, 'male', 34.5, ..., 0, 7.8292, 'Q'],
        [3, 'female', 47.0, ..., 0, 7.0, 'S'],
        [2, 'male', 62.0, ..., 0, 9.6875, 'Q'],
        ...,
        [3, 'male', 38.5, ..., 0, 7.25, 'S'],
        [3, 'male', 21.0, ..., 0, 8.05, 'S'],
        [3, 'male', 21.0, ..., 1, 22.3583, 'C']], dtype=object))

##Take care of the categorical values

In [145]:
# Label Encode Sex
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_train[:, 1] = le.fit_transform(X_train[:, 1])
X_test[:, 1] = le.fit_transform(X_test[:, 1])

In [146]:
X_train, X_train.shape

(array([[3, 1, 22.0, ..., 0, 7.25, 'S'],
        [1, 0, 38.0, ..., 0, 71.2833, 'C'],
        [3, 0, 26.0, ..., 0, 7.925, 'S'],
        ...,
        [3, 0, 24.0, ..., 2, 23.45, 'S'],
        [1, 1, 26.0, ..., 0, 30.0, 'C'],
        [3, 1, 32.0, ..., 0, 7.75, 'Q']], dtype=object), (891, 7))

In [147]:
# One hot encode Embarked
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1])], remainder='passthrough')
X_train = np.array(ct.fit_transform(X_train))
X_test = np.array(ct.fit_transform(X_test))

In [148]:
print(X_test[:5, :])

[[0.0 1.0 0.0 3 1 34.5 0 0 7.8292]
 [0.0 0.0 1.0 3 0 47.0 1 0 7.0]
 [0.0 1.0 0.0 2 1 62.0 0 0 9.6875]
 [0.0 0.0 1.0 3 1 27.0 0 0 8.6625]
 [0.0 0.0 1.0 3 0 22.0 1 1 12.2875]]


##Feature Scaling

In [149]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [150]:
X_train

array([[-0.48204268, -0.30756234,  0.61583843, ...,  0.43279337,
        -0.47367361, -0.50244517],
       [ 2.0745051 , -0.30756234, -1.62380254, ...,  0.43279337,
        -0.47367361,  0.78684529],
       [-0.48204268, -0.30756234,  0.61583843, ..., -0.4745452 ,
        -0.47367361, -0.48885426],
       ...,
       [-0.48204268, -0.30756234,  0.61583843, ...,  0.43279337,
         2.00893337, -0.17626324],
       [ 2.0745051 , -0.30756234, -1.62380254, ..., -0.4745452 ,
        -0.47367361, -0.04438104],
       [-0.48204268,  3.25137334, -1.62380254, ..., -0.4745452 ,
        -0.47367361, -0.49237783]])

##Training the Xgboost Classification model on the Training set

In [151]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier()

In [152]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[252  14]
 [ 30 122]]


0.8947368421052632

##Training the Random Forest Classification model on the Training set

In [153]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [154]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[233  33]
 [ 40 112]]


0.8253588516746412