<a href="https://colab.research.google.com/github/yiwenwangANU/Machine_Learning/blob/main/Numpy_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import numpy as np

#1D np array

In [75]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [77]:
x[1:7:2]

array([1, 3, 5])

In [78]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
x[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
x[-1::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [81]:
x[-3:3:-1]

array([7, 6, 5, 4])

#2D np array

In [82]:
x = np.arange(20).reshape(2, 10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

##Expand dims

In [83]:
x[np.newaxis, ...]

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]])

In [84]:
x[..., np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]]])

In [85]:
x[np.newaxis, :, :]

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]])

In [86]:
x[:, :, np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]]])

In [87]:
np.expand_dims(x, axis=0)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]])

In [88]:
np.expand_dims(x, axis=-1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]]])

##Index for array

In [89]:
x[1:2]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [90]:
x[..., 0]

array([ 0, 10])

In [91]:
x = np.arange(1, 7).reshape(3, 2)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
x[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [93]:
x = np.arange(12).reshape(4, 3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [94]:
row = [[0, 0],
       [3, 3]]
column = [[0, 2],
          [0, 2]]
x[row, column]

array([[ 0,  2],
       [ 9, 11]])

In [95]:
row = [0, 3]
column = [0, 2]
x[np.ix_(row, column)]

array([[ 0,  2],
       [ 9, 11]])

In [96]:
row = np.array([0, 3])
column = np.array([0, 2])
x[row[:, np.newaxis], column]

array([[ 0,  2],
       [ 9, 11]])

In [97]:
x.sum(-1)

array([ 3, 12, 21, 30])

In [98]:
row = x.sum(-1) % 2 == 0
row

array([False,  True, False,  True])

In [99]:
column = [0, 2]
x[np.ix_(row, column)]

array([[ 3,  5],
       [ 9, 11]])

In [100]:
x = np.array([1., -1., -2., 3])
x[x < 0] += 20
x

array([ 1., 19., 18.,  3.])

#Numpy array broadcasting

In [101]:
x = np.arange(4)
y = np.arange(10)[..., np.newaxis]
x+y

array([[ 0,  1,  2,  3],
       [ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12]])